import Head from "next/head";
import Link from "next/link";
import Router, { useRouter } from "next/router";
import {
  ConnectWallet,
  MediaRenderer,
  useActiveListings,
  useAddress,
  useMarketplace,
} from "@thirdweb-dev/react";
import styles from "../styles/Home.module.css";

const CONTRACT_ADDRESS = "0xaF7C92b69446649766D3BCB37C7Ffd2C78e8dA3b";

export default function Home() {
  const address = useAddress();
  const marketplace = useMarketplace(CONTRACT_ADDRESS);
  const { data: listings, isLoading: loadingListings } =
    useActiveListings(marketplace);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <ConnectWallet/> */}
        {loadingListings ? (
          <div>Loading Listings...</div>
        ) : (
          <div>
            {listings?.map((listing) => {
              <div
              key={listing.id}
              onClick={()=> Router.push(`/listing/${listing.id}`)}>
            <MediaRenderer src={listing.asset.image}/>
              <h2>
                <Link href={`/listing/${listing.id}`}>
                  <a>{listing.asset.name}</a>
                </Link>
              </h2>
              <p>
                <strong>{listing.buyoutCurrencyValuePerToken.displayValue}</strong>{" "}{listing.buyoutCurrencyValuePerToken.symbol}
              </p>
              </div>;
            })}
          </div>
        )}
      </main>
    </div>
  );
}
